config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "books#index"

  devise_for :users, skip: :all # authenticate_user! のために残す

  # 不要なアクションを塞ぐために個別に指定
  devise_scope :user do
    get "users/sign_in" => "users/sessions#new", as: :new_user_session
    post "users/sign_in" => "users/sessions#create", as: :user_session
    delete "users/sign_out" => "users/sessions#destroy", as: :destroy_user_session
    get "users/sign_up" => "users/registrations#new", as: :new_user_registration
    post "users" => "users/registrations#create"
    get "users/edit" => "users/registrations#edit", as: :edit_user_registration
    patch "users" => "users/registrations#update"
    put "users" => "users/registrations#update", as: :user_registration
    match "users/auth/github" => "users/omniauth_authorizes#github", as: :user_github_omniauth_authorize, via: [:get, :post]
    match "users/auth/github/callback" => "users/omniauth_callbacks#github", as: :user_github_omniauth_callback, via: [:get, :post]
  end

  resources :users, only: %i[index show] do
    resources :follows, only: %i[create destroy], module: "users"
    resources :followings, only: %i[index], module: "users"
  end

  resources :books do
    resources :comments, only: %i[edit create update destroy], module: "books"
  end

  resources :reports do
    resources :comments, only: %i[edit create update destroy], module: "reports"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
  devise :omniauthable, omniauth_providers: %i[github]

  has_one_attached :avatar

  has_many :active_user_follows, class_name: "UserFollow", foreign_key: :follower_id, inverse_of: :follower
  has_many :followings, through: :active_user_follows

  has_many :reports, dependent: :destroy
  has_many :comments, dependent: :destroy

  attribute :purge_avatar, :boolean, default: false

  class << self
    def from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.last_name = auth.info.last_name
        user.first_name = auth.info.first_name
      end
    end
  end

  def save
    ActiveRecord::Base.transaction do
      super
      avatar.purge if purge_avatar
    end
  end

  # 余裕があればdecoratorにしたいが、速さ優先でmodelに実装
  def full_name
    "#{last_name} #{first_name}" if last_name.present? && first_name.present?
  end
end

app/controllers/users/followings_controller.rb
# frozen_string_literal: true

class Users::FollowingsController < ApplicationController
  def index
    @followings = User.find(params[:user_id]).followings.page(params[:page])
  end
end

app/controllers/users/follows_controller.rb
# frozen_string_literal: true

class Users::FollowsController < ApplicationController
  def create
    @follow = current_user.active_user_follows.build(following_id: params[:user_id])

    if @follow.save
      redirect_to @follow.following, notice: t("view.user/follow.notice.create")
    else
      redirect_to @follow.following, alert: t("view.user/follow.alert.create_failure")
    end
  end

  def destroy
    @follow = current_user.active_user_follows.find(params[:id])
    if @follow.destroy
      redirect_to @follow.following, notice: t("view.user/follow.notice.destroy")
    else
      redirect_to @follow.following, notice: t("view.user/follow.alert.destroy_failure")
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :github

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    #  If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      extra_params = %i[avatar purge_avatar last_name first_name zipcode address introduction]
      devise_parameter_sanitizer.permit(:account_update, keys: extra_params)
    end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end

    def after_update_path_for(resource)
      user_path(current_user)
    end

    def update_resource(resource, params)
      if params[:password].blank? && params[:password_confirmation].blank?
        params.delete(:current_password)
        resource.update_without_password(params)
      else
        resource.update_with_password(params)
      end
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @follow = current_user.active_user_follows.find_or_initialize_by(following: @user)
  end
end

app/views/users/_follow.html.erb
<%= form_with model: follow, url: user_follows_path(follow.following), method: :post do |f| %>
  <% if follow.errors.any? %>
    <ul>
      <% follow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.submit t('view.user/follow.button.create'), style: 'margin-left: 10px; color: #ffffff; background-color: #5cb85c; border-color: #5cc85c; border-radius: 6px' %>
<% end %>

app/views/users/_remove.html.erb
<%= form_with model: follow, url: user_follow_path(follow.following, follow), method: :delete do |f| %>
  <% if follow.errors.any? %>
    <ul>
      <% follow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.submit t('view.user/follow.button.destroy'), style: 'margin-left: 10px; color: #ffffff; background-color: #ef3133; border-color: #EF4133; border-radius: 6px' %>
<% end %>

app/views/users/index.html.erb
<h1><%= t('view.user.title.index') %></h1>

<table>
  <thead>
  <tr>
    <th colspan="1"></th>
    <th><%= User.human_attribute_name(:full_name) %></th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= image_tag user.avatar.variant(resize: "20x20") if user.avatar.attached? %>
      </td>
      <td>
        <%= link_to user.full_name, user_path(user) %>
      </td>
      <% if user == current_user %>
        <td><%= link_to t('view.user.link.edit'), edit_user_registration_path %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @users %>

<br>

app/views/users/show.html.erb
<h1><%= t('view.user.title.show') %></h1>

<div style='display: flex; flex-flow: row nowrap'>
  <%= link_to 'フォローユーザー一覧', user_followings_path(@user) %>
  <% unless @user == current_user %>
    <% if @follow.new_record? %>
      <%= render 'users/follow', follow: @follow %>
    <% else %>
      <%= render 'users/remove', follow: @follow %>
    <% end %>
  <% end %>
</div>

<p>
  <%= image_tag @user.avatar.variant(resize: "100x100") if @user.avatar.attached? %>
</p>

<p>
  <strong><%= User.human_attribute_name(:full_name) %>:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong><%= User.human_attribute_name(:zipcode) %>:</strong>
  <%= @user.zipcode %>
</p>

<p>
  <strong><%= User.human_attribute_name(:address) %>:</strong>
  <%= @user.address %>
</p>

<p>
  <strong><%= User.human_attribute_name(:introduction) %>:</strong>
  <%= @user.introduction %>
</p>

<% if @user == current_user %>
  <%= link_to t('view.user.link.edit'), edit_user_registration_path %> |
<% end %>
<%= link_to t('view.user.link.back'), users_path %>