config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "books#index"

  devise_for :users, skip: :all # authenticate_user! のために残す

  # 不要なアクションを塞ぐために個別に指定
  devise_scope :user do
    get "users/sign_in" => "users/sessions#new", as: :new_user_session
    post "users/sign_in" => "users/sessions#create", as: :user_session
    delete "users/sign_out" => "users/sessions#destroy", as: :destroy_user_session
    get "users/sign_up" => "users/registrations#new", as: :new_user_registration
    post "users" => "users/registrations#create"
    get "users/edit" => "users/registrations#edit", as: :edit_user_registration
    patch "users" => "users/registrations#update"
    put "users" => "users/registrations#update", as: :user_registration
    match "users/auth/github" => "users/omniauth_authorizes#github", as: :user_github_omniauth_authorize, via: [:get, :post]
    match "users/auth/github/callback" => "users/omniauth_callbacks#github", as: :user_github_omniauth_callback, via: [:get, :post]
  end

  resources :users, only: %i[index show] do
    resources :follows, only: %i[create destroy], module: "users"
    resources :followings, only: %i[index], module: "users"
  end

  resources :books do
    resources :comments, only: %i[edit create update destroy], module: "books"
  end

  resources :reports do
    resources :comments, only: %i[edit create update destroy], module: "reports"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validate :more_than_one_report_cannot_be_submitted_on_the_same_day, on: :create

  def reported_on
    created_at&.to_date
  end

  private
    def more_than_one_report_cannot_be_submitted_on_the_same_day
      reports_on_the_same_day = Report.where("created_at BETWEEN ? AND ?", Time.current.beginning_of_day, Time.current.end_of_day)
      if reports_on_the_same_day.exists?
        errors.add(:base, :more_than_one_report_cannot_be_submitted_on_the_same_day)
      end
    end
end

app/controllers/reports/comments_controller.rb
# frozen_string_literal: true

class Reports::CommentsController < ApplicationController
  before_action :set_commentable
  before_action :set_new_comment, only: :create
  before_action :set_comment, only: [:edit, :update, :destroy]

  def edit
  end

  def create
    @comment.user = current_user

    if @comment.save
      redirect_to @commentable, notice: t("view.report/comment.notice.create")
    else
      @comments = @commentable.comments
                         .includes(user: { avatar_attachment: :blob })
                         .order(created_at: :asc)
                         .page(params[:page])
                         .per(10)
      @report = @commentable
      render "reports/show"
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @commentable, notice: t("view.report/comment.notice.update")
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to @commentable, notice: t("view.report/comment.notice.destroy")
  end

  private
  def set_commentable
    resource, id = request.path.split("/")[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  def set_new_comment
    @comment = @commentable.comments.build(comment_params)
  end

  def set_comment
    @comment = @commentable.comments.find_by(id: params[:id], user: current_user)
    redirect_back(fallback_location: root_path) if @comment.blank?
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: [:show]
  before_action :set_users_own_report, only: [:edit, :update, :destroy]

  def index
    @reports = Report.all.page(params[:page])
  end

  def show
    @comments = @report.comments
                       .includes(user: { avatar_attachment: :blob })
                       .order(created_at: :asc)
                       .page(params[:page])
                       .per(10)
    @comment = @report.comments.build
  end

  def new
    @report = current_user.reports.build
  end

  def edit
  end

  def create
    @report = current_user.reports.build(report_params)

    if @report.save
      redirect_to @report, notice: t("view.report.notice.create")
    else
      render :new
    end
  end

  def update
    if @report.update(report_params)
      redirect_to @report, notice: t("view.report.notice.update")
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    redirect_to reports_url, notice: t("view.report.notice.destroy")
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def set_users_own_report
      @report = Report.find_by(id: params[:id], user: current_user)
    end

    def report_params
      params.require(:report).permit(:title, :description)
    end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reported_on %>
    <%= l(report.reported_on || Time.current.to_date) %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, cols: 40, rows: 5 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1><%= t('view.report.title.edit') %></h1>

<%= render 'form', report: @report %>

<%= link_to t('view.report.link.show'), @report %> |
<%= link_to t('view.report.link.back'), reports_path %>

app/views/reports/index.html.erb
<h1><%= t('view.report.title.index') %></h1>

<table>
  <thead>
    <tr>
      <th><%= Report.human_attribute_name(:title) %></th>
      <th><%= Report.human_attribute_name(:reported_on) %></th>
      <th><%= Report.human_attribute_name(:user) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.title %></td>
        <td><%= l(report.reported_on) %></td>
        <td><%= link_to report.user.full_name, user_path(report.user) %></td>
        <td><%= link_to t('view.report.link.show'), report %></td>
        <% if report.user == current_user %>
          <td><%= link_to t('view.report.link.edit'), edit_report_path(report) %></td>
          <td><%= link_to t('view.report.link.destroy'), report, method: :delete, data: { confirm: t('view.report.confirm.destroy') } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @reports %>

<br>

<%= link_to t('view.report.link.new'), new_report_path %>

app/views/reports/new.html.erb
<h1><%= t('view.report.title.new') %></h1>

<%= render 'form', report: @report %>

<%= link_to t('view.report.link.back'), reports_path %>

app/views/reports/show.html.erb
<h1><%= t('view.report.title.show') %></h1>

<h2><%= t('view.report.title.show_detail.show') %></h2>
<p>
  <strong><%= Report.human_attribute_name(:reported_on) %>:</strong>
  <%= l(@report.reported_on) %>
</p>

<p>
  <strong><%= Report.human_attribute_name(:title) %>:</strong>
  <%= @report.title %>
</p>

<p>
  <strong><%= Report.human_attribute_name(:description) %>:</strong>
  <%= @report.description %>
</p>

<% if @report.user == current_user %>
  <%= link_to t('view.report.link.edit'), edit_report_path(@report) %> |
<% end %>
<%= link_to t('view.report.link.back'), reports_path %>

<h2><%= t('view.report.title.show_detail.comments') %></h2>
<%= render 'reports/comments/comments', comments: @comments %>

<h2><%= t('view.report.title.show_detail.comment_form') %></h2>
<%= render 'reports/comments/form', comment: @comment %>