config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "books#index"

  devise_for :users, skip: :all # authenticate_user! のために残す

  # 不要なアクションを塞ぐために個別に指定
  devise_scope :user do
    get "users/sign_in" => "users/sessions#new", as: :new_user_session
    post "users/sign_in" => "users/sessions#create", as: :user_session
    delete "users/sign_out" => "users/sessions#destroy", as: :destroy_user_session
    get "users/sign_up" => "users/registrations#new", as: :new_user_registration
    post "users" => "users/registrations#create"
    get "users/edit" => "users/registrations#edit", as: :edit_user_registration
    patch "users" => "users/registrations#update"
    put "users" => "users/registrations#update", as: :user_registration
    match "users/auth/github" => "users/omniauth_authorizes#github", as: :user_github_omniauth_authorize, via: [:get, :post]
    match "users/auth/github/callback" => "users/omniauth_callbacks#github", as: :user_github_omniauth_callback, via: [:get, :post]
  end

  resources :users, only: %i[index show] do
    resources :follows, only: %i[create destroy], module: "users"
    resources :followings, only: %i[index], module: "users"
  end

  resources :books do
    resources :comments, only: %i[edit create update destroy], module: "books"
  end

  resources :reports do
    resources :comments, only: %i[edit create update destroy], module: "reports"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_menu.html.erb
<% if user_signed_in? %>
  <ul style="border-bottom: #666666 1px solid; padding-bottom: 8px">
    <li><%= link_to t('view.user.title.index'), users_path %></li>
    <li><%= link_to t('view.book.title.index'), books_path %></li>
    <li><%= link_to t('view.report.title.index'), reports_path %></li>
  </ul>
<% end %>

app/views/layouts/_notifications.html.erb
<p id="notice" class="notice"><%= notice %></p>
<p id="alert" class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/notifications" %>
    <%= render "devise/shared/links" %>
    <%= render "layouts/menu" %>
    <%= yield %>
  </body>
</html>